---
driver:
  name: vagrant
  box: g5-nodejs
  box_url: http://files.vagrantup.com/precise64.box

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[g5-nodejs::default]
    attributes: {}
